services:
  server:
    container_name: bme680-server
    build: .
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - influxdb
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7-alpine
    container_name: bme680-influxdb
    ports:
      - "8086:8086"
    environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup
        - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
        - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
        - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
        - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
        - DOCKER_INFLUXDB_INIT_RETENTION=30d
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    volumes:
        - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]

  influxdb_cli:
    image: influxdb:2.7-alpine
    container_name: bme680-influxdb-cli
    environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup
        - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
        - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
        - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
        - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
        - DOCKER_INFLUXDB_INIT_RETENTION=30d
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    entrypoint: >
      /bin/sh -c "
      influx bucket create --skip-verify --name ${INFLUXDB_TELEGRAF_BUCKET} --retention 30d --org ${INFLUXDB_ORG} --host http://influxdb:8086 --token ${INFLUXDB_ADMIN_TOKEN} || 
      if [ \$? -eq 1 ]; then echo 'Bucket already exists, ignoring error.'; else exit 1; fi
      "
    restart: on-failure
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    privileged: true
    ports:
      - "8125:8125"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
    environment:
        - HOST_ETC=/hostfs/etc
        - HOST_PROC=/hostfs/proc
        - HOST_SYS=/hostfs/sys
        - HOST_VAR=/hostfs/var
        - HOST_RUN=/hostfs/run
        - HOST_MOUNT_PREFIX=/hostfs
        - INFLUXDB_URL=http://influxdb:8086
        - INFLUXDB_TOKEN=${INFLUXDB_ADMIN_TOKEN}
        - INFLUXDB_ORG=${INFLUXDB_ORG}
        - INFLUXDB_BUCKET=${INFLUXDB_TELEGRAF_BUCKET}
    restart: unless-stopped
    depends_on:
      - influxdb
      - influxdb_cli

volumes:
    influxdb-data:
    grafana-data:

networks:
  bme680-network:
    external: false
    name: bme680-network