services:
  server:
    container_name: bme680-server
    build: .
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - influxdb
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7-alpine
    container_name: bme680-influxdb
    ports:
      - "8086:8086"
    environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup
        - DOCKER_INFLUXDB_INIT_USERNAME=admin
        - DOCKER_INFLUXDB_INIT_PASSWORD=password
        - DOCKER_INFLUXDB_INIT_ORG=org
        - DOCKER_INFLUXDB_INIT_BUCKET=bucket
        - DOCKER_INFLUXDB_INIT_RETENTION=30d
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
    volumes:
        - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/custom.ini:/usr/share/grafana/conf/custom.ini
    restart: unless-stopped
    depends_on:
      - influxdb


volumes:
    influxdb-data:
    grafana-data:

networks:
  bme680-network:
    external: false
    name: bme680-network